apiVersion : apps/v1
kind: Deployment
metadata:
  name: azk8deployimg 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azk8deployimg
  template:
    metadata:
      labels:
        app: azk8deployimg 
    spec:
      containers:
        - name: azk8deployimg 
          image: qbrainxcicd.azurecr.io/az-k8deploy-img:$(Build.BuildId)
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: azk8deployimg
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: azk8deployimg
