apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: flextest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flextest
  template:
    metadata:
      labels:
        app: flextest
    spec:
      containers:
        - name: flextest
          image: qbrainxcicd.azurecr.io/az-k8deploy-img:22
          ports:
            - containerPort: 80
