apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: flexcub-testing
  labels:
    app: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
        - name: backend-deploy
          image: praveenraj10/k8deploy:15
          ports:
            - containerPort: 80