apiVersion: v1
kind: Service
metadata:
  name: flexcub-app-service
  namespace: flexcub-app
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: flexcub-app-service
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: flexcub-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
